### ISSUE TITLE
Support tooltips on circle layers

### ISSUE THREAD

**Issue by loleg** [cividi/spatial-data-package-platform#48] opened 2021-01-29 16:46 UTC
As in [this example](https://docs.mapbox.com/help/tutorials/make-a-heatmap-with-mapbox-gl-js/#add-some-additional-interactivity), clicking on a circle should open a tooltip, if one is defined through the description attribute.

**Comment by n0rdlicht** [comment] 2021-01-29 17:11
Duplicate of #12

**Closed by n0rdlicht** 2021-01-29 17:11 UTC
