### ISSUE TITLE
UX improvements

### ISSUE THREAD

**Issue by ratron** [cividi/spatial-data-package-platform#47] opened 2021-01-26 10:53 UTC
- [x] When there are no "Weitere Fallbeispiele", don't show the header.
- [x] Hovering over DE shows DE again needlessly.
- [x] Map controls (+/-), scale and info box are overlapping the sidebar on mobile (see [comment](https://github.com/cividi/spatial-data-package-platform/issues/32#issuecomment-766928839))
- [x] "Angebot für Ihre Gemeinde" needs to open in a new tab or a modal dialog.

**Comment by n0rdlicht** [comment] 2021-01-28 13:36
One thing we should fix: Missing image appearing on every page.

Currently there seems to be an issue with loading Fathom (though reporting works fine) – see screenshot from browser console below. This results in a missing image symbol appearing at the end of each page, resulting in a scrollable root view messing up map interactions, overlays etc. @loleg tried fixing this issue by hiding overlays in general (see #42). However, static content pages need to be able to scroll.

Missing image at the end of each page:
<img width="54" alt="Screenshot 2021-01-28 at 14 36 01" src="https://user-images.githubusercontent.com/1425577/106145716-29c8e900-6176-11eb-847a-27eeb7250345.png">

<img width="728" alt="Screenshot 2021-01-28 at 14 31 17" src="https://user-images.githubusercontent.com/1425577/106145664-1b7acd00-6176-11eb-9a19-af741971d5df.png">

**Comment by n0rdlicht** [comment] 2021-02-15 15:42
Fixed by #64 #62 #63 #65

**Comment by n0rdlicht** [comment] 2021-02-18 20:51
Gave this a quick test today on a local installation. Except for the "Weitere Fallbeispiele" everything works well.

For "Weitere Fallbeispiele" the heading seems to appear/disappear accordingly, however the list below is missing.

**Comment by apttx** [comment] 2021-02-23 09:27
@n0rdlicht I moved the list into the same truthiness check as the heading because it wasn't displaying anything. Can you add screenshots of what's missing? I'm unsure what it's supposed to look like.

**Comment by n0rdlicht** [comment] 2021-02-23 09:44
@apttx I did a test with the following setup (three snapshots, one flagged as showcase):

<img width="600" alt="Screenshot 2021-02-23 at 10 39 02" src="https://user-images.githubusercontent.com/1425577/108825709-a4ddbd80-75c3-11eb-8cb4-057a8853a7e1.png">

Works as expected when opening the showcase (no other ones available). 

<img width="600" alt="Screenshot 2021-02-23 at 10 39 22" src="https://user-images.githubusercontent.com/1425577/108825915-e8d0c280-75c3-11eb-9928-71e7c7ef8ac7.png">

However, when opening a non-showcase the header appears but not the entry in the list.

<img width="600" alt="Screenshot 2021-02-23 at 10 39 10" src="https://user-images.githubusercontent.com/1425577/108825952-f9813880-75c3-11eb-8aff-dfa27e77deb1.png">

**Comment by apttx** [comment] 2021-02-25 08:49
@n0rdlicht Seems like it was an issue with SnapshotList and its watched property. Fix is in #72.

**Comment by apttx** [comment] 2021-02-25 09:23
> One thing we should fix: Missing image appearing on every page.

I can't seem to reproduce this, although my console warns me, too. `Loading failed for the <script> with source “https://cdn.usefathom.com/script.js”.`

**Comment by n0rdlicht** [comment] 2021-02-25 10:24
> > One thing we should fix: Missing image appearing on every page.
> 
> I can't seem to reproduce this, although my console warns me, too. `Loading failed for the <script> with source “https://cdn.usefathom.com/script.js”.`

Yep, I had this on other projects as well, not sure what the actual issue is here. Currently to me seems like something on Fathom's end tbh.

**Closed** 2021-03-08 08:38 UTC
Labels: Frontend, bug, enhancement
